// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sample.proto

package kyobobook.grpc.sample;

public interface ResponseResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResponseResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 result_code = 1;</code>
   */
  int getResultCode();

  /**
   * <code>string result_message = 2;</code>
   */
  java.lang.String getResultMessage();
  /**
   * <code>string result_message = 2;</code>
   */
  com.google.protobuf.ByteString
      getResultMessageBytes();

  /**
   * <code>string detail_message = 3;</code>
   */
  java.lang.String getDetailMessage();
  /**
   * <code>string detail_message = 3;</code>
   */
  com.google.protobuf.ByteString
      getDetailMessageBytes();
}
