// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sample.proto

package kyobobook.grpc.sample;

/**
 * Protobuf type {@code SampleRequest}
 */
public  final class SampleRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SampleRequest)
    SampleRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SampleRequest.newBuilder() to construct.
  private SampleRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SampleRequest() {
    seq_ = 0;
    title_ = "";
    contents_ = "";
    txt_ = "";
    reqType_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SampleRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            seq_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            title_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            contents_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            txt_ = s;
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            reqType_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return kyobobook.grpc.sample.SampleProto.internal_static_SampleRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return kyobobook.grpc.sample.SampleProto.internal_static_SampleRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            kyobobook.grpc.sample.SampleRequest.class, kyobobook.grpc.sample.SampleRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code SampleRequest.ReqType}
   */
  public enum ReqType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MASTER = 0;</code>
     */
    MASTER(0),
    /**
     * <code>SLAVE = 1;</code>
     */
    SLAVE(1),
    /**
     * <code>SUB = 2;</code>
     */
    SUB(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MASTER = 0;</code>
     */
    public static final int MASTER_VALUE = 0;
    /**
     * <code>SLAVE = 1;</code>
     */
    public static final int SLAVE_VALUE = 1;
    /**
     * <code>SUB = 2;</code>
     */
    public static final int SUB_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ReqType valueOf(int value) {
      return forNumber(value);
    }

    public static ReqType forNumber(int value) {
      switch (value) {
        case 0: return MASTER;
        case 1: return SLAVE;
        case 2: return SUB;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ReqType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ReqType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ReqType>() {
            public ReqType findValueByNumber(int number) {
              return ReqType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return kyobobook.grpc.sample.SampleRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final ReqType[] VALUES = values();

    public static ReqType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ReqType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SampleRequest.ReqType)
  }

  public static final int SEQ_FIELD_NUMBER = 1;
  private int seq_;
  /**
   * <code>int32 seq = 1;</code>
   */
  public int getSeq() {
    return seq_;
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  private volatile java.lang.Object title_;
  /**
   * <code>string title = 2;</code>
   */
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTENTS_FIELD_NUMBER = 3;
  private volatile java.lang.Object contents_;
  /**
   * <code>string contents = 3;</code>
   */
  public java.lang.String getContents() {
    java.lang.Object ref = contents_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contents_ = s;
      return s;
    }
  }
  /**
   * <code>string contents = 3;</code>
   */
  public com.google.protobuf.ByteString
      getContentsBytes() {
    java.lang.Object ref = contents_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contents_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TXT_FIELD_NUMBER = 4;
  private volatile java.lang.Object txt_;
  /**
   * <code>string txt = 4;</code>
   */
  public java.lang.String getTxt() {
    java.lang.Object ref = txt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      txt_ = s;
      return s;
    }
  }
  /**
   * <code>string txt = 4;</code>
   */
  public com.google.protobuf.ByteString
      getTxtBytes() {
    java.lang.Object ref = txt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      txt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQTYPE_FIELD_NUMBER = 5;
  private int reqType_;
  /**
   * <code>.SampleRequest.ReqType reqType = 5;</code>
   */
  public int getReqTypeValue() {
    return reqType_;
  }
  /**
   * <code>.SampleRequest.ReqType reqType = 5;</code>
   */
  public kyobobook.grpc.sample.SampleRequest.ReqType getReqType() {
    kyobobook.grpc.sample.SampleRequest.ReqType result = kyobobook.grpc.sample.SampleRequest.ReqType.valueOf(reqType_);
    return result == null ? kyobobook.grpc.sample.SampleRequest.ReqType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (seq_ != 0) {
      output.writeInt32(1, seq_);
    }
    if (!getTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
    }
    if (!getContentsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, contents_);
    }
    if (!getTxtBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, txt_);
    }
    if (reqType_ != kyobobook.grpc.sample.SampleRequest.ReqType.MASTER.getNumber()) {
      output.writeEnum(5, reqType_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (seq_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, seq_);
    }
    if (!getTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
    }
    if (!getContentsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, contents_);
    }
    if (!getTxtBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, txt_);
    }
    if (reqType_ != kyobobook.grpc.sample.SampleRequest.ReqType.MASTER.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, reqType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof kyobobook.grpc.sample.SampleRequest)) {
      return super.equals(obj);
    }
    kyobobook.grpc.sample.SampleRequest other = (kyobobook.grpc.sample.SampleRequest) obj;

    boolean result = true;
    result = result && (getSeq()
        == other.getSeq());
    result = result && getTitle()
        .equals(other.getTitle());
    result = result && getContents()
        .equals(other.getContents());
    result = result && getTxt()
        .equals(other.getTxt());
    result = result && reqType_ == other.reqType_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SEQ_FIELD_NUMBER;
    hash = (53 * hash) + getSeq();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + CONTENTS_FIELD_NUMBER;
    hash = (53 * hash) + getContents().hashCode();
    hash = (37 * hash) + TXT_FIELD_NUMBER;
    hash = (53 * hash) + getTxt().hashCode();
    hash = (37 * hash) + REQTYPE_FIELD_NUMBER;
    hash = (53 * hash) + reqType_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static kyobobook.grpc.sample.SampleRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kyobobook.grpc.sample.SampleRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kyobobook.grpc.sample.SampleRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kyobobook.grpc.sample.SampleRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kyobobook.grpc.sample.SampleRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kyobobook.grpc.sample.SampleRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kyobobook.grpc.sample.SampleRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kyobobook.grpc.sample.SampleRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static kyobobook.grpc.sample.SampleRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static kyobobook.grpc.sample.SampleRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static kyobobook.grpc.sample.SampleRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kyobobook.grpc.sample.SampleRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(kyobobook.grpc.sample.SampleRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SampleRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SampleRequest)
      kyobobook.grpc.sample.SampleRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kyobobook.grpc.sample.SampleProto.internal_static_SampleRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kyobobook.grpc.sample.SampleProto.internal_static_SampleRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kyobobook.grpc.sample.SampleRequest.class, kyobobook.grpc.sample.SampleRequest.Builder.class);
    }

    // Construct using kyobobook.grpc.sample.SampleRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      seq_ = 0;

      title_ = "";

      contents_ = "";

      txt_ = "";

      reqType_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return kyobobook.grpc.sample.SampleProto.internal_static_SampleRequest_descriptor;
    }

    public kyobobook.grpc.sample.SampleRequest getDefaultInstanceForType() {
      return kyobobook.grpc.sample.SampleRequest.getDefaultInstance();
    }

    public kyobobook.grpc.sample.SampleRequest build() {
      kyobobook.grpc.sample.SampleRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public kyobobook.grpc.sample.SampleRequest buildPartial() {
      kyobobook.grpc.sample.SampleRequest result = new kyobobook.grpc.sample.SampleRequest(this);
      result.seq_ = seq_;
      result.title_ = title_;
      result.contents_ = contents_;
      result.txt_ = txt_;
      result.reqType_ = reqType_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof kyobobook.grpc.sample.SampleRequest) {
        return mergeFrom((kyobobook.grpc.sample.SampleRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(kyobobook.grpc.sample.SampleRequest other) {
      if (other == kyobobook.grpc.sample.SampleRequest.getDefaultInstance()) return this;
      if (other.getSeq() != 0) {
        setSeq(other.getSeq());
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        onChanged();
      }
      if (!other.getContents().isEmpty()) {
        contents_ = other.contents_;
        onChanged();
      }
      if (!other.getTxt().isEmpty()) {
        txt_ = other.txt_;
        onChanged();
      }
      if (other.reqType_ != 0) {
        setReqTypeValue(other.getReqTypeValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      kyobobook.grpc.sample.SampleRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (kyobobook.grpc.sample.SampleRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int seq_ ;
    /**
     * <code>int32 seq = 1;</code>
     */
    public int getSeq() {
      return seq_;
    }
    /**
     * <code>int32 seq = 1;</code>
     */
    public Builder setSeq(int value) {
      
      seq_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 seq = 1;</code>
     */
    public Builder clearSeq() {
      
      seq_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 2;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     */
    public Builder clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object contents_ = "";
    /**
     * <code>string contents = 3;</code>
     */
    public java.lang.String getContents() {
      java.lang.Object ref = contents_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contents_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string contents = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContentsBytes() {
      java.lang.Object ref = contents_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contents_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contents = 3;</code>
     */
    public Builder setContents(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      contents_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string contents = 3;</code>
     */
    public Builder clearContents() {
      
      contents_ = getDefaultInstance().getContents();
      onChanged();
      return this;
    }
    /**
     * <code>string contents = 3;</code>
     */
    public Builder setContentsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      contents_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object txt_ = "";
    /**
     * <code>string txt = 4;</code>
     */
    public java.lang.String getTxt() {
      java.lang.Object ref = txt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        txt_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string txt = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTxtBytes() {
      java.lang.Object ref = txt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string txt = 4;</code>
     */
    public Builder setTxt(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      txt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string txt = 4;</code>
     */
    public Builder clearTxt() {
      
      txt_ = getDefaultInstance().getTxt();
      onChanged();
      return this;
    }
    /**
     * <code>string txt = 4;</code>
     */
    public Builder setTxtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      txt_ = value;
      onChanged();
      return this;
    }

    private int reqType_ = 0;
    /**
     * <code>.SampleRequest.ReqType reqType = 5;</code>
     */
    public int getReqTypeValue() {
      return reqType_;
    }
    /**
     * <code>.SampleRequest.ReqType reqType = 5;</code>
     */
    public Builder setReqTypeValue(int value) {
      reqType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.SampleRequest.ReqType reqType = 5;</code>
     */
    public kyobobook.grpc.sample.SampleRequest.ReqType getReqType() {
      kyobobook.grpc.sample.SampleRequest.ReqType result = kyobobook.grpc.sample.SampleRequest.ReqType.valueOf(reqType_);
      return result == null ? kyobobook.grpc.sample.SampleRequest.ReqType.UNRECOGNIZED : result;
    }
    /**
     * <code>.SampleRequest.ReqType reqType = 5;</code>
     */
    public Builder setReqType(kyobobook.grpc.sample.SampleRequest.ReqType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      reqType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.SampleRequest.ReqType reqType = 5;</code>
     */
    public Builder clearReqType() {
      
      reqType_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SampleRequest)
  }

  // @@protoc_insertion_point(class_scope:SampleRequest)
  private static final kyobobook.grpc.sample.SampleRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new kyobobook.grpc.sample.SampleRequest();
  }

  public static kyobobook.grpc.sample.SampleRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SampleRequest>
      PARSER = new com.google.protobuf.AbstractParser<SampleRequest>() {
    public SampleRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SampleRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SampleRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SampleRequest> getParserForType() {
    return PARSER;
  }

  public kyobobook.grpc.sample.SampleRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

