// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sample.proto

package kyobobook.grpc.sample;

public final class SampleProto {
  private SampleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SampleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SampleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SampleFieldEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SampleFieldEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SampleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SampleResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Sample.proto\032\033google/protobuf/empty.pr" +
      "oto\"\236\001\n\rSampleRequest\022\013\n\003seq\030\001 \001(\005\022\r\n\005ti" +
      "tle\030\002 \001(\t\022\020\n\010contents\030\003 \001(\t\022\013\n\003txt\030\004 \001(\t" +
      "\022\'\n\007reqType\030\005 \001(\0162\026.SampleRequest.ReqTyp" +
      "e\")\n\007ReqType\022\n\n\006MASTER\020\000\022\t\n\005SLAVE\020\001\022\007\n\003S" +
      "UB\020\002\"]\n\020SampleFieldEntry\022\013\n\003seq\030\001 \001(\005\022\r\n" +
      "\005title\030\002 \001(\t\022\020\n\010contents\030\003 \001(\t\022\013\n\003txt\030\004 " +
      "\001(\t\022\016\n\006result\030\005 \001(\010\"3\n\016SampleResponse\022!\n" +
      "\006result\030\001 \001(\0132\021.SampleFieldEntry2\257\002\n\006Sam" +
      "ple\0227\n\020SelectGrpcSample\022\016.SampleRequest\032" +
      "\017.SampleResponse\"\0000\001\0222\n\rGetGrpcSample\022\016." +
      "SampleRequest\032\017.SampleResponse\"\000\022<\n\020Inse" +
      "rtGrpcSample\022\016.SampleRequest\032\026.google.pr" +
      "otobuf.Empty\"\000\022<\n\020UpdateGrpcSample\022\016.Sam" +
      "pleRequest\032\026.google.protobuf.Empty\"\000\022<\n\020" +
      "DeleteGrpcSample\022\016.SampleRequest\032\026.googl" +
      "e.protobuf.Empty\"\000B&\n\025kyobobook.grpc.sam" +
      "pleB\013SampleProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_SampleRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SampleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SampleRequest_descriptor,
        new java.lang.String[] { "Seq", "Title", "Contents", "Txt", "ReqType", });
    internal_static_SampleFieldEntry_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SampleFieldEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SampleFieldEntry_descriptor,
        new java.lang.String[] { "Seq", "Title", "Contents", "Txt", "Result", });
    internal_static_SampleResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SampleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SampleResponse_descriptor,
        new java.lang.String[] { "Result", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
