// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sample.proto

package kyobobook.grpc.sample;

public interface SampleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SampleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.SampleFieldEntry result = 1;</code>
   */
  boolean hasResult();
  /**
   * <code>.SampleFieldEntry result = 1;</code>
   */
  kyobobook.grpc.sample.SampleFieldEntry getResult();
  /**
   * <code>.SampleFieldEntry result = 1;</code>
   */
  kyobobook.grpc.sample.SampleFieldEntryOrBuilder getResultOrBuilder();

  /**
   * <code>.ResponseResult responseResult = 2;</code>
   */
  boolean hasResponseResult();
  /**
   * <code>.ResponseResult responseResult = 2;</code>
   */
  kyobobook.grpc.sample.ResponseResult getResponseResult();
  /**
   * <code>.ResponseResult responseResult = 2;</code>
   */
  kyobobook.grpc.sample.ResponseResultOrBuilder getResponseResultOrBuilder();
}
