// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sample.proto

package kyobobook.grpc.sample;

public interface SampleFieldEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SampleFieldEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 seq = 1;</code>
   */
  int getSeq();

  /**
   * <code>string title = 2;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string contents = 3;</code>
   */
  java.lang.String getContents();
  /**
   * <code>string contents = 3;</code>
   */
  com.google.protobuf.ByteString
      getContentsBytes();

  /**
   * <code>string txt = 4;</code>
   */
  java.lang.String getTxt();
  /**
   * <code>string txt = 4;</code>
   */
  com.google.protobuf.ByteString
      getTxtBytes();

  /**
   * <code>bool result = 5;</code>
   */
  boolean getResult();
}
