// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test.proto

package kyobobook.grpc.test;

/**
 * Protobuf type {@code TestResponse}
 */
public  final class TestResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TestResponse)
    TestResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TestResponse.newBuilder() to construct.
  private TestResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TestResponse() {
    ordrId_ = "";
    ordrDate_ = "";
    ordrHms_ = "";
    mmbrLgnId_ = "";
    aordName_ = "";
    aordPrtbTlnm_ = "";
    aordIpAdrs_ = "";
    adrs_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TestResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            ordrId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            ordrDate_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            ordrHms_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            mmbrLgnId_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            aordName_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            aordPrtbTlnm_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            aordIpAdrs_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            adrs_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return kyobobook.grpc.test.TestProto.internal_static_TestResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return kyobobook.grpc.test.TestProto.internal_static_TestResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            kyobobook.grpc.test.TestResponse.class, kyobobook.grpc.test.TestResponse.Builder.class);
  }

  public static final int ORDRID_FIELD_NUMBER = 1;
  private volatile java.lang.Object ordrId_;
  /**
   * <code>string ordrId = 1;</code>
   */
  public java.lang.String getOrdrId() {
    java.lang.Object ref = ordrId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ordrId_ = s;
      return s;
    }
  }
  /**
   * <code>string ordrId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getOrdrIdBytes() {
    java.lang.Object ref = ordrId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ordrId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORDRDATE_FIELD_NUMBER = 2;
  private volatile java.lang.Object ordrDate_;
  /**
   * <code>string ordrDate = 2;</code>
   */
  public java.lang.String getOrdrDate() {
    java.lang.Object ref = ordrDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ordrDate_ = s;
      return s;
    }
  }
  /**
   * <code>string ordrDate = 2;</code>
   */
  public com.google.protobuf.ByteString
      getOrdrDateBytes() {
    java.lang.Object ref = ordrDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ordrDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORDRHMS_FIELD_NUMBER = 3;
  private volatile java.lang.Object ordrHms_;
  /**
   * <code>string ordrHms = 3;</code>
   */
  public java.lang.String getOrdrHms() {
    java.lang.Object ref = ordrHms_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ordrHms_ = s;
      return s;
    }
  }
  /**
   * <code>string ordrHms = 3;</code>
   */
  public com.google.protobuf.ByteString
      getOrdrHmsBytes() {
    java.lang.Object ref = ordrHms_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ordrHms_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MMBRLGNID_FIELD_NUMBER = 4;
  private volatile java.lang.Object mmbrLgnId_;
  /**
   * <code>string mmbrLgnId = 4;</code>
   */
  public java.lang.String getMmbrLgnId() {
    java.lang.Object ref = mmbrLgnId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mmbrLgnId_ = s;
      return s;
    }
  }
  /**
   * <code>string mmbrLgnId = 4;</code>
   */
  public com.google.protobuf.ByteString
      getMmbrLgnIdBytes() {
    java.lang.Object ref = mmbrLgnId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mmbrLgnId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AORDNAME_FIELD_NUMBER = 5;
  private volatile java.lang.Object aordName_;
  /**
   * <code>string aordName = 5;</code>
   */
  public java.lang.String getAordName() {
    java.lang.Object ref = aordName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      aordName_ = s;
      return s;
    }
  }
  /**
   * <code>string aordName = 5;</code>
   */
  public com.google.protobuf.ByteString
      getAordNameBytes() {
    java.lang.Object ref = aordName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      aordName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AORDPRTBTLNM_FIELD_NUMBER = 6;
  private volatile java.lang.Object aordPrtbTlnm_;
  /**
   * <code>string aordPrtbTlnm = 6;</code>
   */
  public java.lang.String getAordPrtbTlnm() {
    java.lang.Object ref = aordPrtbTlnm_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      aordPrtbTlnm_ = s;
      return s;
    }
  }
  /**
   * <code>string aordPrtbTlnm = 6;</code>
   */
  public com.google.protobuf.ByteString
      getAordPrtbTlnmBytes() {
    java.lang.Object ref = aordPrtbTlnm_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      aordPrtbTlnm_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AORDIPADRS_FIELD_NUMBER = 7;
  private volatile java.lang.Object aordIpAdrs_;
  /**
   * <code>string aordIpAdrs = 7;</code>
   */
  public java.lang.String getAordIpAdrs() {
    java.lang.Object ref = aordIpAdrs_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      aordIpAdrs_ = s;
      return s;
    }
  }
  /**
   * <code>string aordIpAdrs = 7;</code>
   */
  public com.google.protobuf.ByteString
      getAordIpAdrsBytes() {
    java.lang.Object ref = aordIpAdrs_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      aordIpAdrs_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADRS_FIELD_NUMBER = 8;
  private volatile java.lang.Object adrs_;
  /**
   * <code>string adrs = 8;</code>
   */
  public java.lang.String getAdrs() {
    java.lang.Object ref = adrs_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      adrs_ = s;
      return s;
    }
  }
  /**
   * <code>string adrs = 8;</code>
   */
  public com.google.protobuf.ByteString
      getAdrsBytes() {
    java.lang.Object ref = adrs_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      adrs_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getOrdrIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ordrId_);
    }
    if (!getOrdrDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ordrDate_);
    }
    if (!getOrdrHmsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ordrHms_);
    }
    if (!getMmbrLgnIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, mmbrLgnId_);
    }
    if (!getAordNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, aordName_);
    }
    if (!getAordPrtbTlnmBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, aordPrtbTlnm_);
    }
    if (!getAordIpAdrsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, aordIpAdrs_);
    }
    if (!getAdrsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, adrs_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getOrdrIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ordrId_);
    }
    if (!getOrdrDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ordrDate_);
    }
    if (!getOrdrHmsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ordrHms_);
    }
    if (!getMmbrLgnIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, mmbrLgnId_);
    }
    if (!getAordNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, aordName_);
    }
    if (!getAordPrtbTlnmBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, aordPrtbTlnm_);
    }
    if (!getAordIpAdrsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, aordIpAdrs_);
    }
    if (!getAdrsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, adrs_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof kyobobook.grpc.test.TestResponse)) {
      return super.equals(obj);
    }
    kyobobook.grpc.test.TestResponse other = (kyobobook.grpc.test.TestResponse) obj;

    boolean result = true;
    result = result && getOrdrId()
        .equals(other.getOrdrId());
    result = result && getOrdrDate()
        .equals(other.getOrdrDate());
    result = result && getOrdrHms()
        .equals(other.getOrdrHms());
    result = result && getMmbrLgnId()
        .equals(other.getMmbrLgnId());
    result = result && getAordName()
        .equals(other.getAordName());
    result = result && getAordPrtbTlnm()
        .equals(other.getAordPrtbTlnm());
    result = result && getAordIpAdrs()
        .equals(other.getAordIpAdrs());
    result = result && getAdrs()
        .equals(other.getAdrs());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ORDRID_FIELD_NUMBER;
    hash = (53 * hash) + getOrdrId().hashCode();
    hash = (37 * hash) + ORDRDATE_FIELD_NUMBER;
    hash = (53 * hash) + getOrdrDate().hashCode();
    hash = (37 * hash) + ORDRHMS_FIELD_NUMBER;
    hash = (53 * hash) + getOrdrHms().hashCode();
    hash = (37 * hash) + MMBRLGNID_FIELD_NUMBER;
    hash = (53 * hash) + getMmbrLgnId().hashCode();
    hash = (37 * hash) + AORDNAME_FIELD_NUMBER;
    hash = (53 * hash) + getAordName().hashCode();
    hash = (37 * hash) + AORDPRTBTLNM_FIELD_NUMBER;
    hash = (53 * hash) + getAordPrtbTlnm().hashCode();
    hash = (37 * hash) + AORDIPADRS_FIELD_NUMBER;
    hash = (53 * hash) + getAordIpAdrs().hashCode();
    hash = (37 * hash) + ADRS_FIELD_NUMBER;
    hash = (53 * hash) + getAdrs().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static kyobobook.grpc.test.TestResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kyobobook.grpc.test.TestResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kyobobook.grpc.test.TestResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kyobobook.grpc.test.TestResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kyobobook.grpc.test.TestResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kyobobook.grpc.test.TestResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kyobobook.grpc.test.TestResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kyobobook.grpc.test.TestResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static kyobobook.grpc.test.TestResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static kyobobook.grpc.test.TestResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static kyobobook.grpc.test.TestResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kyobobook.grpc.test.TestResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(kyobobook.grpc.test.TestResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TestResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TestResponse)
      kyobobook.grpc.test.TestResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kyobobook.grpc.test.TestProto.internal_static_TestResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kyobobook.grpc.test.TestProto.internal_static_TestResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kyobobook.grpc.test.TestResponse.class, kyobobook.grpc.test.TestResponse.Builder.class);
    }

    // Construct using kyobobook.grpc.test.TestResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      ordrId_ = "";

      ordrDate_ = "";

      ordrHms_ = "";

      mmbrLgnId_ = "";

      aordName_ = "";

      aordPrtbTlnm_ = "";

      aordIpAdrs_ = "";

      adrs_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return kyobobook.grpc.test.TestProto.internal_static_TestResponse_descriptor;
    }

    public kyobobook.grpc.test.TestResponse getDefaultInstanceForType() {
      return kyobobook.grpc.test.TestResponse.getDefaultInstance();
    }

    public kyobobook.grpc.test.TestResponse build() {
      kyobobook.grpc.test.TestResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public kyobobook.grpc.test.TestResponse buildPartial() {
      kyobobook.grpc.test.TestResponse result = new kyobobook.grpc.test.TestResponse(this);
      result.ordrId_ = ordrId_;
      result.ordrDate_ = ordrDate_;
      result.ordrHms_ = ordrHms_;
      result.mmbrLgnId_ = mmbrLgnId_;
      result.aordName_ = aordName_;
      result.aordPrtbTlnm_ = aordPrtbTlnm_;
      result.aordIpAdrs_ = aordIpAdrs_;
      result.adrs_ = adrs_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof kyobobook.grpc.test.TestResponse) {
        return mergeFrom((kyobobook.grpc.test.TestResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(kyobobook.grpc.test.TestResponse other) {
      if (other == kyobobook.grpc.test.TestResponse.getDefaultInstance()) return this;
      if (!other.getOrdrId().isEmpty()) {
        ordrId_ = other.ordrId_;
        onChanged();
      }
      if (!other.getOrdrDate().isEmpty()) {
        ordrDate_ = other.ordrDate_;
        onChanged();
      }
      if (!other.getOrdrHms().isEmpty()) {
        ordrHms_ = other.ordrHms_;
        onChanged();
      }
      if (!other.getMmbrLgnId().isEmpty()) {
        mmbrLgnId_ = other.mmbrLgnId_;
        onChanged();
      }
      if (!other.getAordName().isEmpty()) {
        aordName_ = other.aordName_;
        onChanged();
      }
      if (!other.getAordPrtbTlnm().isEmpty()) {
        aordPrtbTlnm_ = other.aordPrtbTlnm_;
        onChanged();
      }
      if (!other.getAordIpAdrs().isEmpty()) {
        aordIpAdrs_ = other.aordIpAdrs_;
        onChanged();
      }
      if (!other.getAdrs().isEmpty()) {
        adrs_ = other.adrs_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      kyobobook.grpc.test.TestResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (kyobobook.grpc.test.TestResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object ordrId_ = "";
    /**
     * <code>string ordrId = 1;</code>
     */
    public java.lang.String getOrdrId() {
      java.lang.Object ref = ordrId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ordrId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ordrId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOrdrIdBytes() {
      java.lang.Object ref = ordrId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ordrId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ordrId = 1;</code>
     */
    public Builder setOrdrId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ordrId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ordrId = 1;</code>
     */
    public Builder clearOrdrId() {
      
      ordrId_ = getDefaultInstance().getOrdrId();
      onChanged();
      return this;
    }
    /**
     * <code>string ordrId = 1;</code>
     */
    public Builder setOrdrIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ordrId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ordrDate_ = "";
    /**
     * <code>string ordrDate = 2;</code>
     */
    public java.lang.String getOrdrDate() {
      java.lang.Object ref = ordrDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ordrDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ordrDate = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOrdrDateBytes() {
      java.lang.Object ref = ordrDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ordrDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ordrDate = 2;</code>
     */
    public Builder setOrdrDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ordrDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ordrDate = 2;</code>
     */
    public Builder clearOrdrDate() {
      
      ordrDate_ = getDefaultInstance().getOrdrDate();
      onChanged();
      return this;
    }
    /**
     * <code>string ordrDate = 2;</code>
     */
    public Builder setOrdrDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ordrDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ordrHms_ = "";
    /**
     * <code>string ordrHms = 3;</code>
     */
    public java.lang.String getOrdrHms() {
      java.lang.Object ref = ordrHms_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ordrHms_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ordrHms = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOrdrHmsBytes() {
      java.lang.Object ref = ordrHms_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ordrHms_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ordrHms = 3;</code>
     */
    public Builder setOrdrHms(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ordrHms_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ordrHms = 3;</code>
     */
    public Builder clearOrdrHms() {
      
      ordrHms_ = getDefaultInstance().getOrdrHms();
      onChanged();
      return this;
    }
    /**
     * <code>string ordrHms = 3;</code>
     */
    public Builder setOrdrHmsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ordrHms_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object mmbrLgnId_ = "";
    /**
     * <code>string mmbrLgnId = 4;</code>
     */
    public java.lang.String getMmbrLgnId() {
      java.lang.Object ref = mmbrLgnId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mmbrLgnId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mmbrLgnId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMmbrLgnIdBytes() {
      java.lang.Object ref = mmbrLgnId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mmbrLgnId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mmbrLgnId = 4;</code>
     */
    public Builder setMmbrLgnId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mmbrLgnId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string mmbrLgnId = 4;</code>
     */
    public Builder clearMmbrLgnId() {
      
      mmbrLgnId_ = getDefaultInstance().getMmbrLgnId();
      onChanged();
      return this;
    }
    /**
     * <code>string mmbrLgnId = 4;</code>
     */
    public Builder setMmbrLgnIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mmbrLgnId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object aordName_ = "";
    /**
     * <code>string aordName = 5;</code>
     */
    public java.lang.String getAordName() {
      java.lang.Object ref = aordName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        aordName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string aordName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAordNameBytes() {
      java.lang.Object ref = aordName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aordName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string aordName = 5;</code>
     */
    public Builder setAordName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      aordName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string aordName = 5;</code>
     */
    public Builder clearAordName() {
      
      aordName_ = getDefaultInstance().getAordName();
      onChanged();
      return this;
    }
    /**
     * <code>string aordName = 5;</code>
     */
    public Builder setAordNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      aordName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object aordPrtbTlnm_ = "";
    /**
     * <code>string aordPrtbTlnm = 6;</code>
     */
    public java.lang.String getAordPrtbTlnm() {
      java.lang.Object ref = aordPrtbTlnm_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        aordPrtbTlnm_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string aordPrtbTlnm = 6;</code>
     */
    public com.google.protobuf.ByteString
        getAordPrtbTlnmBytes() {
      java.lang.Object ref = aordPrtbTlnm_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aordPrtbTlnm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string aordPrtbTlnm = 6;</code>
     */
    public Builder setAordPrtbTlnm(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      aordPrtbTlnm_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string aordPrtbTlnm = 6;</code>
     */
    public Builder clearAordPrtbTlnm() {
      
      aordPrtbTlnm_ = getDefaultInstance().getAordPrtbTlnm();
      onChanged();
      return this;
    }
    /**
     * <code>string aordPrtbTlnm = 6;</code>
     */
    public Builder setAordPrtbTlnmBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      aordPrtbTlnm_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object aordIpAdrs_ = "";
    /**
     * <code>string aordIpAdrs = 7;</code>
     */
    public java.lang.String getAordIpAdrs() {
      java.lang.Object ref = aordIpAdrs_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        aordIpAdrs_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string aordIpAdrs = 7;</code>
     */
    public com.google.protobuf.ByteString
        getAordIpAdrsBytes() {
      java.lang.Object ref = aordIpAdrs_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aordIpAdrs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string aordIpAdrs = 7;</code>
     */
    public Builder setAordIpAdrs(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      aordIpAdrs_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string aordIpAdrs = 7;</code>
     */
    public Builder clearAordIpAdrs() {
      
      aordIpAdrs_ = getDefaultInstance().getAordIpAdrs();
      onChanged();
      return this;
    }
    /**
     * <code>string aordIpAdrs = 7;</code>
     */
    public Builder setAordIpAdrsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      aordIpAdrs_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object adrs_ = "";
    /**
     * <code>string adrs = 8;</code>
     */
    public java.lang.String getAdrs() {
      java.lang.Object ref = adrs_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        adrs_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string adrs = 8;</code>
     */
    public com.google.protobuf.ByteString
        getAdrsBytes() {
      java.lang.Object ref = adrs_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        adrs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string adrs = 8;</code>
     */
    public Builder setAdrs(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      adrs_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string adrs = 8;</code>
     */
    public Builder clearAdrs() {
      
      adrs_ = getDefaultInstance().getAdrs();
      onChanged();
      return this;
    }
    /**
     * <code>string adrs = 8;</code>
     */
    public Builder setAdrsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      adrs_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TestResponse)
  }

  // @@protoc_insertion_point(class_scope:TestResponse)
  private static final kyobobook.grpc.test.TestResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new kyobobook.grpc.test.TestResponse();
  }

  public static kyobobook.grpc.test.TestResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TestResponse>
      PARSER = new com.google.protobuf.AbstractParser<TestResponse>() {
    public TestResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TestResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TestResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TestResponse> getParserForType() {
    return PARSER;
  }

  public kyobobook.grpc.test.TestResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

