// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test.proto

package kyobobook.grpc.test;

public interface TestResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TestResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ordrId = 1;</code>
   */
  java.lang.String getOrdrId();
  /**
   * <code>string ordrId = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrdrIdBytes();

  /**
   * <code>string ordrDate = 2;</code>
   */
  java.lang.String getOrdrDate();
  /**
   * <code>string ordrDate = 2;</code>
   */
  com.google.protobuf.ByteString
      getOrdrDateBytes();

  /**
   * <code>string ordrHms = 3;</code>
   */
  java.lang.String getOrdrHms();
  /**
   * <code>string ordrHms = 3;</code>
   */
  com.google.protobuf.ByteString
      getOrdrHmsBytes();

  /**
   * <code>string mmbrLgnId = 4;</code>
   */
  java.lang.String getMmbrLgnId();
  /**
   * <code>string mmbrLgnId = 4;</code>
   */
  com.google.protobuf.ByteString
      getMmbrLgnIdBytes();

  /**
   * <code>string aordName = 5;</code>
   */
  java.lang.String getAordName();
  /**
   * <code>string aordName = 5;</code>
   */
  com.google.protobuf.ByteString
      getAordNameBytes();

  /**
   * <code>string aordPrtbTlnm = 6;</code>
   */
  java.lang.String getAordPrtbTlnm();
  /**
   * <code>string aordPrtbTlnm = 6;</code>
   */
  com.google.protobuf.ByteString
      getAordPrtbTlnmBytes();

  /**
   * <code>string aordIpAdrs = 7;</code>
   */
  java.lang.String getAordIpAdrs();
  /**
   * <code>string aordIpAdrs = 7;</code>
   */
  com.google.protobuf.ByteString
      getAordIpAdrsBytes();

  /**
   * <code>string adrs = 8;</code>
   */
  java.lang.String getAdrs();
  /**
   * <code>string adrs = 8;</code>
   */
  com.google.protobuf.ByteString
      getAdrsBytes();
}
