// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test.proto

package kyobobook.grpc.test;

public final class TestProto {
  private TestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TestRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TestResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nTest.proto\032\033google/protobuf/empty.prot" +
      "o\"\035\n\013TestRequest\022\016\n\006ordrId\030\001 \001(\t\"\236\001\n\014Tes" +
      "tResponse\022\016\n\006ordrId\030\001 \001(\t\022\020\n\010ordrDate\030\002 " +
      "\001(\t\022\017\n\007ordrHms\030\003 \001(\t\022\021\n\tmmbrLgnId\030\004 \001(\t\022" +
      "\020\n\010aordName\030\005 \001(\t\022\024\n\014aordPrtbTlnm\030\006 \001(\t\022" +
      "\022\n\naordIpAdrs\030\007 \001(\t\022\014\n\004adrs\030\010 \001(\t2i\n\004Tes" +
      "t\0227\n\nSelectData\022\026.google.protobuf.Empty\032" +
      "\r.TestResponse\"\0000\001\022(\n\007GetData\022\014.TestRequ" +
      "est\032\r.TestResponse\"\000B\"\n\023kyobobook.grpc.t" +
      "estB\tTestProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_TestRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TestRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TestRequest_descriptor,
        new java.lang.String[] { "OrdrId", });
    internal_static_TestResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TestResponse_descriptor,
        new java.lang.String[] { "OrdrId", "OrdrDate", "OrdrHms", "MmbrLgnId", "AordName", "AordPrtbTlnm", "AordIpAdrs", "Adrs", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
