// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test.proto

package kyobobook.grpc.test;

public interface TestRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TestRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ordrId = 1;</code>
   */
  java.lang.String getOrdrId();
  /**
   * <code>string ordrId = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrdrIdBytes();
}
