server:
  port: 8070

spring:
  master:
    datasource:
      jdbc-url: jdbc:log4jdbc:postgresql://129.100.253.37:5444/master
      username: admin
      password: pass
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  slave:
    datasource:
      jdbc-url: jdbc:log4jdbc:postgresql://129.100.253.37:5444/slave
      username: admin
      password: pass
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      
#      jdbc-url: jdbc:log4jdbc:postgresql://127.0.0.1:5432/master
#      username: kyobo
#      password: kyobo!@#
#      jdbc-url: jdbc:log4jdbc:postgresql://127.0.0.1:5432/slave
#      username: kyobo
#      password: kyobo!@#

gpring:
  application:
    name: local-grpc-client
    
grpc:
  client:
    local-grpc-server:
      address: 'static://kyobobook-rpc.prototype.svc.cluster.local:9898'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext