server:
  port: 8070
  
spring:
  writer:
    datasource:
      jdbc-url: jdbc:log4jdbc:postgresql://aws-tst-rosa-db1-proto.cluster-cnfj3o94pok7.ap-northeast-2.rds.amazonaws.com:5432/prototype
      username: postgres
      password: postgres12345
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  reader:
    datasource:
      jdbc-url: jdbc:log4jdbc:postgresql://aws-tst-rosa-db1-proto.cluster-ro-cnfj3o94pok7.ap-northeast-2.rds.amazonaws.com:5432/prototype
      username: postgres
      password: postgres12345
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

gpring:
  application:
    name: common-prototype-api
    
grpc:
  server:
    port: 8075
  client:
    common-prototype-sub-api:
      address: 'dns:///common-prototype-sub-api.prototype.svc.cluster.local:8065'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext