server:
  port: 8070

spring:
  application:
    name: common-prototype-api
  writer:
    datasource:
      jdbc-url: jdbc:log4jdbc:postgresql://129.100.253.37:3000/DEVDB_TMP
      username: dbadmin
      password: password
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  reader:
    datasource:
      jdbc-url: jdbc:log4jdbc:postgresql://129.100.253.37:3000/DEVDB_TMP
      username: dbadmin
      password: password
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  cache:
    type: redis
    redis:
      cache-null-values: false
      use-key-prefix: true
      key-prefix: prototype
  redis:
    host: 129.100.253.38
    port: 6379
    password: password
    timeout: 10000
  data:
    mongodb:
      uri: mongodb://129.100.253.41:27017/admin
      database: admin
      username: dbadmin
      password: password
      authentication-database: admin
      
# rest api 사용시 호출될 서비스 정보
resource:
  common-prototype-sub-api:
    url: http://localhost:8060
    
gpring:
  application:
    name: common-prototype-api
    
grpc:
  server:
    port: 8075
    maxInboundMessageSize: 15MB
  client:
    common-prototype-sub-api:
      address: 'static://localhost:8065'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext