server:
  port: 8070

spring:
  writer:
    datasource:
      jdbc-url: jdbc:log4jdbc:postgresql://129.100.253.37:3000/DEVDB_TMP
      username: dbadmin
      password: password
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  reader:
    datasource:
      jdbc-url: jdbc:log4jdbc:postgresql://129.100.253.37:3000/DEVDB_TMP
      username: dbadmin
      password: password
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      
# rest api 사용시 호출될 서비스 정보
resource:
  common-prototype-sub-api:
    url: http://localhost:8060
    
      
gpring:
  application:
    name: common-prototype-api
    
grpc:
  server:
    port: 8075
    maxInboundMessageSize: 15MB
  client:
    common-prototype-sub-api:
      address: 'static://localhost:8065'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext