server:
  port: 8070
  
spring:
  master:
    datasource:
      jdbc-url: jdbc:log4jdbc:postgresql://aws-tst-rosa-db1-proto.cluster-cnfj3o94pok7.ap-northeast-2.rds.amazonaws.com:5432/master
      username: postgres
      password: postgres12345
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  slave:
    datasource:
      jdbc-url: jdbc:log4jdbc:postgresql://aws-tst-rosa-db1-proto.cluster-cnfj3o94pok7.ap-northeast-2.rds.amazonaws.com:5432/slave
      username: postgres
      password: postgres12345
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

gpring:
  application:
    name: local-grpc-client
    
grpc:
  client:
    local-grpc-server:
      address: 'dns:///kyobobook-grpc.prototype.svc.cluster.local:9898'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext