server:
  port: 8070

spring:
  master:
    datasource:
      jdbc-url: jdbc:log4jdbc:postgresql://aws-tst-rosa-db1-proto.cluster-cnfj3o94pok7.ap-northeast-2.rds.amazonaws.com:3000/master
      username: postgres
      password: postgres12345
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  slave:
    datasource:
      jdbc-url: jdbc:log4jdbc:postgresql://aws-tst-rosa-db1-proto.cluster-cnfj3o94pok7.ap-northeast-2.rds.amazonaws.com:3000/slave
      username: postgres
      password: postgres12345
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      
gpring:
  application:
    name: common-prototype-api
    
grpc:
  server:
    port: 8075
  client:
    common-prototype-sub-api:
      address: 'static://localhost:8065'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext