// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

package kyobobook.grpc.product;

public interface ProductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ProductFieldEntry result = 1;</code>
   */
  boolean hasResult();
  /**
   * <code>.ProductFieldEntry result = 1;</code>
   */
  kyobobook.grpc.product.ProductFieldEntry getResult();
  /**
   * <code>.ProductFieldEntry result = 1;</code>
   */
  kyobobook.grpc.product.ProductFieldEntryOrBuilder getResultOrBuilder();

  /**
   * <code>.ResponseResult responseResult = 2;</code>
   */
  boolean hasResponseResult();
  /**
   * <code>.ResponseResult responseResult = 2;</code>
   */
  kyobobook.grpc.sample.ResponseResult getResponseResult();
  /**
   * <code>.ResponseResult responseResult = 2;</code>
   */
  kyobobook.grpc.sample.ResponseResultOrBuilder getResponseResultOrBuilder();
}
