// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

package kyobobook.grpc.product;

public interface ProductFieldEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductFieldEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cmdt_id = 1;</code>
   */
  java.lang.String getCmdtId();
  /**
   * <code>string cmdt_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getCmdtIdBytes();

  /**
   * <code>string bkrv_cntt = 2;</code>
   */
  java.lang.String getBkrvCntt();
  /**
   * <code>string bkrv_cntt = 2;</code>
   */
  com.google.protobuf.ByteString
      getBkrvCnttBytes();

  /**
   * <code>string ctnt_cntt = 3;</code>
   */
  java.lang.String getCtntCntt();
  /**
   * <code>string ctnt_cntt = 3;</code>
   */
  com.google.protobuf.ByteString
      getCtntCnttBytes();
}
