// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

package kyobobook.grpc.product;

public final class ProductProto {
  private ProductProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductFieldEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductFieldEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rProduct.proto\032\014Sample.proto\"G\n\016Product" +
      "Request\022\017\n\007cmdt_id\030\001 \001(\t\022\021\n\tbkrv_cntt\030\002 " +
      "\001(\t\022\021\n\tctnt_cntt\030\003 \001(\t\"J\n\021ProductFieldEn" +
      "try\022\017\n\007cmdt_id\030\001 \001(\t\022\021\n\tbkrv_cntt\030\002 \001(\t\022" +
      "\021\n\tctnt_cntt\030\003 \001(\t\"^\n\017ProductResponse\022\"\n" +
      "\006result\030\001 \001(\0132\022.ProductFieldEntry\022\'\n\016res" +
      "ponseResult\030\002 \001(\0132\017.ResponseResult2\252\002\n\007P" +
      "roduct\0227\n\020GetProductDetail\022\017.ProductRequ" +
      "est\032\020.ProductResponse\"\000\0227\n\021InsertProduct" +
      "Bkrv\022\017.ProductRequest\032\017.ResponseResult\"\000" +
      "\0227\n\021InsertProductCtnt\022\017.ProductRequest\032\017" +
      ".ResponseResult\"\000\0229\n\023UpdateProductDetail" +
      "\022\017.ProductRequest\032\017.ResponseResult\"\000\0229\n\023" +
      "DeleteProductDetail\022\017.ProductRequest\032\017.R" +
      "esponseResult\"\000B(\n\026kyobobook.grpc.produc" +
      "tB\014ProductProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          kyobobook.grpc.sample.SampleProto.getDescriptor(),
        }, assigner);
    internal_static_ProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductRequest_descriptor,
        new java.lang.String[] { "CmdtId", "BkrvCntt", "CtntCntt", });
    internal_static_ProductFieldEntry_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProductFieldEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductFieldEntry_descriptor,
        new java.lang.String[] { "CmdtId", "BkrvCntt", "CtntCntt", });
    internal_static_ProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductResponse_descriptor,
        new java.lang.String[] { "Result", "ResponseResult", });
    kyobobook.grpc.sample.SampleProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
