// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

package kyobobook.grpc.product;

/**
 * Protobuf type {@code ProductRequest}
 */
public  final class ProductRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ProductRequest)
    ProductRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProductRequest.newBuilder() to construct.
  private ProductRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProductRequest() {
    cmdtId_ = "";
    bkrvCntt_ = "";
    ctntCntt_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProductRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            cmdtId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            bkrvCntt_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            ctntCntt_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return kyobobook.grpc.product.ProductProto.internal_static_ProductRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return kyobobook.grpc.product.ProductProto.internal_static_ProductRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            kyobobook.grpc.product.ProductRequest.class, kyobobook.grpc.product.ProductRequest.Builder.class);
  }

  public static final int CMDT_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object cmdtId_;
  /**
   * <code>string cmdt_id = 1;</code>
   */
  public java.lang.String getCmdtId() {
    java.lang.Object ref = cmdtId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cmdtId_ = s;
      return s;
    }
  }
  /**
   * <code>string cmdt_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCmdtIdBytes() {
    java.lang.Object ref = cmdtId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cmdtId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BKRV_CNTT_FIELD_NUMBER = 2;
  private volatile java.lang.Object bkrvCntt_;
  /**
   * <code>string bkrv_cntt = 2;</code>
   */
  public java.lang.String getBkrvCntt() {
    java.lang.Object ref = bkrvCntt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bkrvCntt_ = s;
      return s;
    }
  }
  /**
   * <code>string bkrv_cntt = 2;</code>
   */
  public com.google.protobuf.ByteString
      getBkrvCnttBytes() {
    java.lang.Object ref = bkrvCntt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bkrvCntt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CTNT_CNTT_FIELD_NUMBER = 3;
  private volatile java.lang.Object ctntCntt_;
  /**
   * <code>string ctnt_cntt = 3;</code>
   */
  public java.lang.String getCtntCntt() {
    java.lang.Object ref = ctntCntt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ctntCntt_ = s;
      return s;
    }
  }
  /**
   * <code>string ctnt_cntt = 3;</code>
   */
  public com.google.protobuf.ByteString
      getCtntCnttBytes() {
    java.lang.Object ref = ctntCntt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ctntCntt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCmdtIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cmdtId_);
    }
    if (!getBkrvCnttBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, bkrvCntt_);
    }
    if (!getCtntCnttBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ctntCntt_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCmdtIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cmdtId_);
    }
    if (!getBkrvCnttBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, bkrvCntt_);
    }
    if (!getCtntCnttBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ctntCntt_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof kyobobook.grpc.product.ProductRequest)) {
      return super.equals(obj);
    }
    kyobobook.grpc.product.ProductRequest other = (kyobobook.grpc.product.ProductRequest) obj;

    boolean result = true;
    result = result && getCmdtId()
        .equals(other.getCmdtId());
    result = result && getBkrvCntt()
        .equals(other.getBkrvCntt());
    result = result && getCtntCntt()
        .equals(other.getCtntCntt());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CMDT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCmdtId().hashCode();
    hash = (37 * hash) + BKRV_CNTT_FIELD_NUMBER;
    hash = (53 * hash) + getBkrvCntt().hashCode();
    hash = (37 * hash) + CTNT_CNTT_FIELD_NUMBER;
    hash = (53 * hash) + getCtntCntt().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static kyobobook.grpc.product.ProductRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kyobobook.grpc.product.ProductRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kyobobook.grpc.product.ProductRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kyobobook.grpc.product.ProductRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kyobobook.grpc.product.ProductRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kyobobook.grpc.product.ProductRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kyobobook.grpc.product.ProductRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kyobobook.grpc.product.ProductRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static kyobobook.grpc.product.ProductRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static kyobobook.grpc.product.ProductRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static kyobobook.grpc.product.ProductRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kyobobook.grpc.product.ProductRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(kyobobook.grpc.product.ProductRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ProductRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ProductRequest)
      kyobobook.grpc.product.ProductRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kyobobook.grpc.product.ProductProto.internal_static_ProductRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kyobobook.grpc.product.ProductProto.internal_static_ProductRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kyobobook.grpc.product.ProductRequest.class, kyobobook.grpc.product.ProductRequest.Builder.class);
    }

    // Construct using kyobobook.grpc.product.ProductRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      cmdtId_ = "";

      bkrvCntt_ = "";

      ctntCntt_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return kyobobook.grpc.product.ProductProto.internal_static_ProductRequest_descriptor;
    }

    public kyobobook.grpc.product.ProductRequest getDefaultInstanceForType() {
      return kyobobook.grpc.product.ProductRequest.getDefaultInstance();
    }

    public kyobobook.grpc.product.ProductRequest build() {
      kyobobook.grpc.product.ProductRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public kyobobook.grpc.product.ProductRequest buildPartial() {
      kyobobook.grpc.product.ProductRequest result = new kyobobook.grpc.product.ProductRequest(this);
      result.cmdtId_ = cmdtId_;
      result.bkrvCntt_ = bkrvCntt_;
      result.ctntCntt_ = ctntCntt_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof kyobobook.grpc.product.ProductRequest) {
        return mergeFrom((kyobobook.grpc.product.ProductRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(kyobobook.grpc.product.ProductRequest other) {
      if (other == kyobobook.grpc.product.ProductRequest.getDefaultInstance()) return this;
      if (!other.getCmdtId().isEmpty()) {
        cmdtId_ = other.cmdtId_;
        onChanged();
      }
      if (!other.getBkrvCntt().isEmpty()) {
        bkrvCntt_ = other.bkrvCntt_;
        onChanged();
      }
      if (!other.getCtntCntt().isEmpty()) {
        ctntCntt_ = other.ctntCntt_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      kyobobook.grpc.product.ProductRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (kyobobook.grpc.product.ProductRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object cmdtId_ = "";
    /**
     * <code>string cmdt_id = 1;</code>
     */
    public java.lang.String getCmdtId() {
      java.lang.Object ref = cmdtId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cmdtId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cmdt_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCmdtIdBytes() {
      java.lang.Object ref = cmdtId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmdtId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cmdt_id = 1;</code>
     */
    public Builder setCmdtId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cmdtId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cmdt_id = 1;</code>
     */
    public Builder clearCmdtId() {
      
      cmdtId_ = getDefaultInstance().getCmdtId();
      onChanged();
      return this;
    }
    /**
     * <code>string cmdt_id = 1;</code>
     */
    public Builder setCmdtIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cmdtId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object bkrvCntt_ = "";
    /**
     * <code>string bkrv_cntt = 2;</code>
     */
    public java.lang.String getBkrvCntt() {
      java.lang.Object ref = bkrvCntt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bkrvCntt_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bkrv_cntt = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBkrvCnttBytes() {
      java.lang.Object ref = bkrvCntt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bkrvCntt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bkrv_cntt = 2;</code>
     */
    public Builder setBkrvCntt(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bkrvCntt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string bkrv_cntt = 2;</code>
     */
    public Builder clearBkrvCntt() {
      
      bkrvCntt_ = getDefaultInstance().getBkrvCntt();
      onChanged();
      return this;
    }
    /**
     * <code>string bkrv_cntt = 2;</code>
     */
    public Builder setBkrvCnttBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bkrvCntt_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ctntCntt_ = "";
    /**
     * <code>string ctnt_cntt = 3;</code>
     */
    public java.lang.String getCtntCntt() {
      java.lang.Object ref = ctntCntt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ctntCntt_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ctnt_cntt = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCtntCnttBytes() {
      java.lang.Object ref = ctntCntt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ctntCntt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ctnt_cntt = 3;</code>
     */
    public Builder setCtntCntt(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ctntCntt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ctnt_cntt = 3;</code>
     */
    public Builder clearCtntCntt() {
      
      ctntCntt_ = getDefaultInstance().getCtntCntt();
      onChanged();
      return this;
    }
    /**
     * <code>string ctnt_cntt = 3;</code>
     */
    public Builder setCtntCnttBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ctntCntt_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ProductRequest)
  }

  // @@protoc_insertion_point(class_scope:ProductRequest)
  private static final kyobobook.grpc.product.ProductRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new kyobobook.grpc.product.ProductRequest();
  }

  public static kyobobook.grpc.product.ProductRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProductRequest>
      PARSER = new com.google.protobuf.AbstractParser<ProductRequest>() {
    public ProductRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProductRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProductRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProductRequest> getParserForType() {
    return PARSER;
  }

  public kyobobook.grpc.product.ProductRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

